In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.decomposition import NMF
import pickle

In [3]:
ratings = pd.read_csv('./ratings_matrix_original.csv', index_col=0)

In [4]:
ratings.head()

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
ratings.T.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
'71 (2014),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
'Hellboy': The Seeds of Creation (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Round Midnight (1986),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Salem's Lot (2004),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Til There Was You (1997),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
mean_user_ratings = ratings.transpose().fillna(round(ratings.mean(axis=1), 1)).transpose().head()

In [6]:
mean_user_ratings.head()

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.4,4.4,4.4,4.4,4.4,4.4,4.4,4.4,4.4,4.4,...,4.4,4.4,4.4,4.4,4.4,4.4,4.4,4.4,4.0,4.4
2,3.9,3.9,3.9,3.9,3.9,3.9,3.9,3.9,3.9,3.9,...,3.9,3.9,3.9,3.9,3.9,3.9,3.9,3.9,3.9,3.9
3,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,...,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4
4,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,...,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6
5,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,...,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6

In [7]:
median_user_ratings = ratings.transpose().fillna(round(ratings.median(axis=1), 1)).transpose().head()

In [8]:
median_user_ratings.head()

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0
2,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
3,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
4,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
5,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0

In [43]:
min_user_ratings = ratings.transpose().fillna(round(ratings.min(axis=1), 1)).transpose().head()

In [44]:
min_user_ratings.head()

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0
2,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
3,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,...,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [22]:
max_user_ratings = ratings.transpose().fillna(round(ratings.max(axis=1), 1)).transpose()

In [23]:
max_user_ratings.head()

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0
2,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
3,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
4,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
5,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0

## NMF with mean user rating

In [24]:
n_components = 20
nmf= NMF(n_components=n_components, max_iter=500)

In [25]:
nmf.fit(mean_user_ratings)

NMF(max_iter=500, n_components=20)

In [26]:
Q = pd.DataFrame(nmf.components_, columns=list(mean_user_ratings.columns), 
                 index=[f"cluster_{i+1}" for i in range(n_components)])

In [27]:
Q.head(2)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
cluster_1,0.221609,0.350709,0.249568,0.307904,0.293379,0.278477,0.461868,0.165298,0.281114,0.124582,...,0.437754,0.408729,0.498205,0.43836,0.351135,0.515649,0.463205,0.508036,0.478213,0.196308
cluster_2,0.666777,0.645113,0.400364,0.435213,0.180068,0.269593,0.294977,0.276057,0.494226,0.816433,...,0.218163,0.119422,0.346944,0.45141,0.088136,0.109053,0.108725,0.215803,0.224737,0.609368

In [28]:
P = pd.DataFrame(nmf.transform(mean_user_ratings),
             index=mean_user_ratings.index,
            columns = [f"cluster_{i+1}" for i in range(n_components)])

In [29]:
P.head(2)

,cluster_1,cluster_2,cluster_3,cluster_4,cluster_5,cluster_6,cluster_7,cluster_8,cluster_9,cluster_10,cluster_11,cluster_12,cluster_13,cluster_14,cluster_15,cluster_16,cluster_17,cluster_18,cluster_19,cluster_20
userId,,,,,,,,,,,,,,,,,,,,
1,4.961196,2.136095,1.140891,0.626711,0.550027,0.561581,0.014237,0.045239,0.116074,0.598199,0.281615,0.303655,0.069916,0.038712,0.184006,0.016226,0.431419,0.071257,0.400777,0.340776
2,2.915125,1.929470,1.004458,0.633973,0.234511,0.202318,0.292731,0.233822,0.083770,0.570612,0.104688,0.229270,0.862865,0.363034,0.204318,0.517843,0.326172,0.262314,0.236845,0.256650

In [30]:
R_hat = pd.DataFrame(np.dot(P, Q), 
             index=mean_user_ratings.index,
            columns=list(mean_user_ratings.columns))

In [31]:
abs(mean_user_ratings - R_hat)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.000357,0.000190,0.000300,0.000187,0.000669,0.000040,0.000846,0.000717,0.000234,0.000628,...,0.000243,0.000117,0.000558,0.000001,0.000584,0.000096,0.000212,0.000547,0.000359,0.000589
2,0.000272,0.000210,0.000226,0.000088,0.000359,0.000118,0.000480,0.000408,0.000257,0.000398,...,0.000130,0.000010,0.000310,0.000053,0.000389,0.000212,0.000180,0.000309,0.000670,0.000114
3,0.000197,0.000575,0.000402,0.000071,0.000428,0.000190,0.000778,0.000793,0.000219,0.000515,...,0.000339,0.000090,0.000271,0.000339,0.000316,0.000097,0.000237,0.000723,0.002291,0.000217
4,0.000066,0.000271,0.000160,0.000282,0.000030,0.000189,0.000126,0.000158,0.000151,0.000116,...,0.000021,0.000091,0.000015,0.000208,0.000085,0.000295,0.000063,0.000271,0.001250,0.000232
5,0.000892,0.000477,0.000587,0.000621,0.000888,0.000454,0.001105,0.000852,0.000980,0.001074,...,0.000184,0.000020,0.000869,0.000009,0.001245,0.001298,0.000554,0.000471,0.001204,0.000122

In [32]:
nmf.reconstruction_err_

0.2323975563670328

## NMF with median user rating

In [33]:
n_components = 20
nmf= NMF(n_components=n_components, max_iter=500)

In [34]:
nmf.fit(median_user_ratings)

NMF(max_iter=500, n_components=20)

In [35]:
Q = pd.DataFrame(nmf.components_, columns=list(median_user_ratings.columns), 
                 index=[f"cluster_{i+1}" for i in range(n_components)])

In [36]:
Q.head(2)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
cluster_1,0.357914,0.247678,0.441488,0.105997,0.186761,0.524586,0.586337,0.463450,0.524904,0.346619,...,0.101153,0.387149,0.417143,0.047999,0.344511,0.129961,0.218070,0.543525,0.051909,0.293604
cluster_2,0.522638,0.392692,0.108675,1.076485,0.548436,0.069217,0.029282,0.140908,0.129871,0.021833,...,0.547222,0.542343,0.346877,0.728750,0.479962,0.690870,0.624747,0.073632,0.508581,0.379880

In [37]:
P = pd.DataFrame(nmf.transform(median_user_ratings),
             index=median_user_ratings.index,
            columns = [f"cluster_{i+1}" for i in range(n_components)])

In [38]:
P.head(2)

,cluster_1,cluster_2,cluster_3,cluster_4,cluster_5,cluster_6,cluster_7,cluster_8,cluster_9,cluster_10,cluster_11,cluster_12,cluster_13,cluster_14,cluster_15,cluster_16,cluster_17,cluster_18,cluster_19,cluster_20
userId,,,,,,,,,,,,,,,,,,,,
1,5.078118,2.092852,0.792120,0.432628,0.523622,0.671560,0.686718,0.089391,0.243491,0.454065,0.558785,0.404966,0.268228,0.707551,0.284284,0.171001,0.123337,0.548107,0.444727,0.065810
2,3.544964,1.645127,0.703731,0.678109,0.403149,0.592898,0.396819,0.199843,0.364632,0.016041,0.113657,0.301558,0.163148,0.205941,0.393803,0.179796,0.492169,0.467016,0.487928,0.373319

In [39]:
R_hat = pd.DataFrame(np.dot(P, Q), 
             index=median_user_ratings.index,
            columns=list(median_user_ratings.columns))

In [40]:
abs(median_user_ratings - R_hat)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.000129,0.000907,0.000569,0.000027,0.000757,0.000423,0.000554,0.001190,0.000181,0.001090,...,0.000314,0.000097,0.000111,0.000886,0.001590,0.001097,0.000432,0.000022,0.001642,0.000545
2,0.000136,0.000285,0.000277,0.000015,0.000707,0.000488,0.000440,0.000836,0.000308,0.000442,...,0.000621,0.000061,0.000218,0.001018,0.001333,0.000229,0.000115,0.000080,0.000543,0.000398
3,0.000098,0.000036,0.000250,0.000027,0.000114,0.000019,0.000182,0.000023,0.000042,0.000015,...,0.000150,0.000195,0.000039,0.000184,0.000171,0.000221,0.000011,0.000292,0.000225,0.000106
4,0.000563,0.000379,0.000283,0.000174,0.000289,0.000250,0.000207,0.000225,0.000498,0.000640,...,0.000823,0.000286,0.000342,0.000495,0.001243,0.000634,0.000150,0.000179,0.001726,0.000454
5,0.000381,0.000201,0.000223,0.000222,0.000342,0.000408,0.000607,0.000746,0.000268,0.000547,...,0.000541,0.000281,0.000115,0.000602,0.001356,0.000147,0.000208,0.000167,0.000808,0.000201

In [41]:
nmf.reconstruction_err_

0.39317450257821773

## NMF with min user rating

In [42]:
n_components = 20
nmf= NMF(n_components=n_components, max_iter=500)

In [45]:
nmf.fit(min_user_ratings)

NMF(max_iter=500, n_components=20)

In [46]:
Q = pd.DataFrame(nmf.components_, columns=list(min_user_ratings.columns), 
                 index=[f"cluster_{i+1}" for i in range(n_components)])

In [47]:
Q.head(2)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
cluster_1,0.241170,0.076362,0.324196,0.274285,0.073067,0.277956,0.032083,0.252912,0.330729,0.372217,...,0.249728,0.001128,0.378641,0.104549,0.326114,0.119877,0.230772,0.362278,0.217276,0.275741
cluster_2,0.242923,0.347055,0.157108,0.047061,0.434762,0.104738,0.500635,0.064178,0.034638,0.067907,...,0.204957,0.253170,0.049492,0.261647,0.043976,0.259317,0.270499,0.054621,0.289559,0.164281

In [48]:
P = pd.DataFrame(nmf.transform(min_user_ratings),
             index=min_user_ratings.index,
            columns = [f"cluster_{i+1}" for i in range(n_components)])

In [49]:
P.head(2)

,cluster_1,cluster_2,cluster_3,cluster_4,cluster_5,cluster_6,cluster_7,cluster_8,cluster_9,cluster_10,cluster_11,cluster_12,cluster_13,cluster_14,cluster_15,cluster_16,cluster_17,cluster_18,cluster_19,cluster_20
userId,,,,,,,,,,,,,,,,,,,,
1,1.560313,0.704581,0.511388,0.000755,0.000176,0.534409,0.00908,0.032058,0.079316,0.549709,0.027630,0.577446,0.008278,0.253085,0.053804,0.034671,0.312525,0.318657,0.000000,0.160558
2,3.593605,1.853441,0.729981,1.114800,0.278894,0.000232,0.02883,0.000095,0.538838,0.196494,0.423749,0.006362,0.328635,0.124502,0.000086,0.000000,0.369237,0.000000,0.000523,0.409542

In [50]:
R_hat = pd.DataFrame(np.dot(P, Q), 
             index=min_user_ratings.index,
            columns=list(min_user_ratings.columns))

In [51]:
abs(min_user_ratings - R_hat)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.000004,0.000260,0.000127,0.000076,0.000019,0.000226,0.000134,0.000193,0.000004,0.000034,...,0.000084,0.000098,0.000136,0.000008,0.000193,0.000101,0.000015,0.000117,0.000053,0.000062
2,0.000002,0.000194,0.000195,0.000060,0.000077,0.000123,0.000064,0.000173,0.000029,0.000040,...,0.000145,0.000057,0.000196,0.000012,0.000070,0.000116,0.000028,0.000185,0.000020,0.000178
3,0.000015,0.000087,0.000126,0.000059,0.000107,0.000083,0.000080,0.000164,0.000002,0.000038,...,0.000041,0.000029,0.000067,0.000111,0.000062,0.000080,0.000065,0.000164,0.000035,0.000139
4,0.000003,0.000126,0.000147,0.000083,0.000122,0.000121,0.000037,0.000139,0.000070,0.000018,...,0.000023,0.000065,0.000147,0.000041,0.000012,0.000055,0.000037,0.000040,0.000046,0.000103
5,0.000035,0.000024,0.000033,0.000373,0.000224,0.000152,0.000310,0.000241,0.000087,0.000067,...,0.000081,0.000295,0.000003,0.000237,0.000014,0.000045,0.000072,0.000375,0.000127,0.000243

In [52]:
nmf.reconstruction_err_

0.04669012193205572

## NMF with max user rating

In [53]:
n_components = 20
nmf= NMF(n_components=n_components, max_iter=500)

In [54]:
nmf.fit(max_user_ratings)

NMF(max_iter=500, n_components=20)

In [55]:
Q = pd.DataFrame(nmf.components_, columns=list(max_user_ratings.columns), 
                 index=[f"cluster_{i+1}" for i in range(n_components)])

In [56]:
Q.head(2)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
cluster_1,0.300057,2.106388,2.292162,2.278872,2.036215,2.227106,1.125915,0.270800,1.795896,0.478439,...,2.325407,0.369713,0.237302,0.189594,2.077401,1.722408,0.000000,0.000000,1.390862,2.071719
cluster_2,42.077159,34.762974,30.094339,28.761239,22.964819,27.450869,0.000000,1.928347,72.512797,35.282759,...,28.335982,45.589257,42.755116,45.531847,23.762687,0.000000,106.992418,76.492037,0.000000,16.884542

In [57]:
P = pd.DataFrame(nmf.transform(max_user_ratings),
             index=max_user_ratings.index,
            columns = [f"cluster_{i+1}" for i in range(n_components)])

/Users/abhi/miniconda3/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:1692: ConvergenceWarning: Maximum number of iterations 500 reached. Increase it to improve convergence.
  warnings.warn(

In [58]:
P.head(2)

,cluster_1,cluster_2,cluster_3,cluster_4,cluster_5,cluster_6,cluster_7,cluster_8,cluster_9,cluster_10,cluster_11,cluster_12,cluster_13,cluster_14,cluster_15,cluster_16,cluster_17,cluster_18,cluster_19,cluster_20
userId,,,,,,,,,,,,,,,,,,,,
1,0.318090,0.009907,0.010540,0.0,0.001890,0.034109,0.000222,0.009102,0.012926,0.019608,0.024305,0.415869,0.470716,0.31574,0.019912,0.186709,0.421624,0.091482,0.0,0.0
2,0.300014,0.010044,0.011754,0.0,0.005955,0.037003,0.000217,0.010383,0.013879,0.029545,0.017704,0.430982,0.490294,0.33145,0.021493,0.168199,0.403486,0.070117,0.0,0.0

In [59]:
R_hat = pd.DataFrame(np.dot(P, Q), 
             index=max_user_ratings.index,
            columns=list(max_user_ratings.columns))

In [60]:
abs(max_user_ratings - R_hat)

,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.034472,0.003655,0.005700,0.010178,0.002218,0.003034,0.029152,0.001239,0.008487,0.044358,...,0.005689,0.043619,0.027198,0.030995,0.003169,0.050226,0.000155,0.018080,0.903295,0.005444
2,0.020022,0.000606,0.004402,0.007737,0.000070,0.010887,0.027523,0.000870,0.029929,0.040429,...,0.006955,0.027238,0.011031,0.013971,0.000130,0.001853,0.053799,0.016798,0.056700,0.001129
3,0.013552,0.001195,0.000295,0.002525,0.000082,0.011668,0.047067,0.015313,0.023657,0.028866,...,0.001927,0.006841,0.017549,0.019955,0.000158,0.011563,0.041669,0.000195,0.027338,0.007092
4,0.029406,0.005436,0.015212,0.020160,0.002095,0.007691,0.111638,0.010530,0.019841,0.029793,...,0.014469,0.037561,0.024222,0.034007,0.003503,0.010643,0.067147,0.019106,0.131021,0.001399
5,0.021659,0.000451,0.006238,0.007996,0.003666,0.009829,0.004762,0.007876,0.020110,0.022401,...,0.003088,0.029612,0.021565,0.025066,0.003275,0.041144,0.028457,0.004556,0.090541,0.005561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.124581,0.011227,0.034574,0.038324,0.116721,0.045610,0.367071,0.212028,0.239560,0.079543,...,0.039172,0.026248,0.109269,0.094822,0.118007,0.243349,0.174673,0.050357,0.190383,0.143881
607,0.022466,0.005151,0.000921,0.005818,0.000783,0.008979,0.018865,0.008557,0.029305,0.060456,...,0.016951,0.024608,0.006998,0.010414,0.000399,0.042043,0.027835,0.006406,0.101359,0.002331
608,0.016437,0.052334,0.080458,0.065706,0.098669,0.028268,1.127526,0.034755,0.145460,0.619063,...,0.069299,0.165254,0.051659,0.057234,0.104708,0.207565,0.850108,0.130051,1.465840,0.054253
609,0.016122,0.000384,0.003470,0.006140,0.000432,0.006369,0.019150,0.003870,0.009279,0.030107,...,0.001826,0.026022,0.007577,0.009992,0.000448,0.011173,0.036117,0.008103,0.044517,0.002011
610,0.642945,0.021650,0.086182,0.083500,0.051632,0.046699,0.221747,0.188991,0.875965,0.139629,...,0.094709,0.657276,0.821296,1.264614,0.054641,0.118195,1.308195,2.605569,0.271116,0.035802

In [61]:
nmf.reconstruction_err_

468.3468012090084

## NMF with knn

In [ ]:
n_components = 20
nmf= NMF(n_components=n_components, max_iter=500)

In [ ]:
nmf.fit(knn_imputed_rating)

In [ ]:
Q = pd.DataFrame(nmf.components_, columns=list(knn_imputed_rating.columns), 
                 index=[f"cluster_{i+1}" for i in range(n_components)])

In [ ]:
Q.head(2)

In [ ]:
P = pd.DataFrame(nmf.transform(knn_imputed_rating),
             index=knn_imputed_rating.index,
            columns = [f"cluster_{i+1}" for i in range(n_components)])

In [ ]:
P.head(2)

In [ ]:
R_hat = pd.DataFrame(np.dot(P, Q), 
             index=knn_imputed_rating.index,
            columns=list(knn_imputed_rating.columns))

In [ ]:
abs(knn_imputed_rating - R_hat)

In [ ]:
nmf.reconstruction_err_